import React from "react";
import styles from './ServiceProviders.module.css'

function ServiceProviders(){
    return(
        <>
        <div className={`mt-3 pt-5 container ${styles.cursor}`}>
            <h2 className="fw-light ms-3">SERVICE PROVIDERS</h2>
            <p className="ms-4">Like many businesses, SH uses a range of service providers to help us maximise the quality and efficiency of our services and business operations. This means that individuals and organisations outside of SH, such as mail houses, will sometimes have access to personal information held by SH and may use it on behalf of SH. We require our service providers to adhere to strict privacy guidelines and not to keep this information or use it for unauthorised purposes.</p>
            <h2 className="fw-light ms-3">SH and Marketing Activities</h2>
            <p>SH manages communications with members, prospective members and customers according to its privacy policy. We respect individuals' choices when contacting us for marketing purposes. We may occasionally contact you by the email, by WhatsApp, on-call / SMS or at other address that you provide to us to:</p>
            <ol className={`ms-3 ${styles.ull}`}>
                <li className="ms-4">Remind you of your offers, benefits and other details</li>
                <li className="ms-4">Provide you with updated information about our services or special promotions</li>
                <li className="ms-4"> Provide you with other information about other products and services which you may have an interest in </li>
            </ol>
            <p>Some of this information is necessary for our communication about the SH programme and is sent to all users. However, if you are receiving promotional information from SH and do not wish to receive it any longer, you may remove your name from our list by mailing us at  feedback@starholidays.com and asking to be removed from our mailing list. Please allow 28 days for this request to be processed.</p>
            <h2 className="ms-3 fw-light">For Our Website Users</h2>
            <p className="ms-4">SH is committed to high standards of data security regarding information collected on our site. We offer SSL encryption, the industry-standard security measure for transactions made over the Internet.</p>
            <p className="ms-4">New technologies are emerging on the Internet that help us deliver customised visitor experiences. At SH, we primarily use "cookies" to help us determine which service and support information is appropriate for your computer and to facilitate your use of our instant transactions area. Using this technology does not mean we automatically collect additional information about you. We might be able to ascertain what type of computer you are using, but beyond that, our use of cookies is designed only to provide you with a better experience when using our websites.  As you know, a cookie is a small file stored on your computer when you visit a website. If you revisit the website, the cookie shows that it is a repeat visit. The cookie does not contain any personal information and cannot be used to identify you on third-party websites, including the websites of the analysis provider.  Furthermore, cookies can be used to store your preferred settings, e.g., language and country settings, so that these are available immediately upon your next visit.  We do not use IP addresses or cookies to identify you personally. We use the web analytics system to increase the efficiency of our site.  SH uses industry-standard tools and practices like Google Analytics, Adwords, Affiliate Networks and Social Media Platforms to interact with customers and measure their behaviour on our digital platforms.
            </p>
            <p className="ms-4">Users can also voluntarily subscribe to newsletters, offers, and official information via website, email, social media, and other channel partners.</p>
            <p className="ms-4">SH assumes full responsibility for its customer information in digital and non-digital formats</p>
            <p className="ms-4">SH does not disclose/leak or share its customer information to unauthorised agencies.</p>
            <p className="ms-4">We want to be sure you understand that accepting a cookie in no way gives us access to your computer or any personal information about you.</p>
            <h2 className="fw-light ms-3">Website Tracking Methods used By SH</h2>
            <p className="ms-4">We use Google Analytics to help us better understand how visitors use this website and to facilitate interest-based advertising associated with your Google Account and other devices you use.  The information generated by the Google Analytics cookie about your use of this website is transmitted to and stored by Google.  If you do not want your activity on this website to be tracked by Google Analytics, you may opt-out by using the link http://tools.google.com/dlpage/gaoptout?hl=en </p>
            <h2 className="fw-light ms-3">Newsletter</h2>
            <p className="ms-4">Should you wish to receive the newsletter offered on the website, we require a valid email address and information that allows us to verify that you are the owner of the email address and that the owner agrees to receive the newsletter.You may, at any time, revoke your consent to the storage of the data and email address and their use for sending the newsletter.
            </p>
            <h2 className="fw-light ms-3">Security</h2>
            <p className="ms-4">SH stores and operates all the information of the website and customer data in a web server transmitted via sha256RSA encrypted https protocol. SH also runs a redundant server to avoid loss of info/data. SH takes responsibility of the information/identity security on the owned digital properties. In the case of external websites and digital properties, users should refer to the privacy policy of the respective external websites and public platforms.</p>
            <h2 className="fw-light ms-3">Blog</h2>
            <p className="ms-4">Your email address must be a subscriber to our blog, and it is stored exclusively for communication purposes. The address is not used for other services.If you have any questions about SH blogs, don't hesitate to get in touch with us at: feedback@starholidays.com 
            </p>
        </div>
        </>
    )
}

export default ServiceProviders;